// Keep in sync with backend/src/constants/enums.js and shared/schemas/case-enums.json
export const CASE_TYPES = ['Civil', 'Criminal', 'Family', 'Property', 'Commercial', 'Consumer', 'Labour', 'Cheque Bounce'];
export const COURTS = ['District Court', 'Sessions Court', 'High Court', 'Family Court', 'Consumer Forum', 'Magistrate Court'];
export const STAGES = ['Filing', 'Admission', 'Notice Issued', 'Pleadings', 'Evidence', 'Arguments', 'Judgment Reserved'];
export const STATUSES = ['Pending', 'Adjourned', 'Stayed', 'Disposed'];
export const PRIORITIES = ['Low', 'Normal', 'High', 'Urgent'];
export const RISK_LEVELS = ['HIGH', 'MEDIUM', 'LOW'];
export const STATES = [
  'Andhra Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
  'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan',
  'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

export const RISK_COLORS = { HIGH: '#b42318', MEDIUM: '#b54708', LOW: '#067647', UNASSESSED: '#98a2b3' };
export const CHART_COLORS = ['#232b40', '#b8892b', '#56658a', '#0e7490', '#7c3aed', '#be185d', '#4d7c0f', '#a7b1c7'];

export const PREDICTION_DISCLAIMER =
  'This prediction is generated by an AI/ML model for research and decision-support purposes. It is not a legal judgment or guarantee.';
export const RECOMMENDATION_DISCLAIMER =
  'Recommendations are administrative decision-support suggestions generated by a rule engine. They are not legal advice or judicial orders.';
export const SHAP_DISCLAIMER =
  'Model feature contribution (SHAP): shows how each input influenced the model’s output. It does not prove real-world causation.';
export const SYNTHETIC_DATA_NOTE =
  'The bundled model is trained on synthetic sample data intended only for development/testing.';
